user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

mvms_api:
    type: rest
    prefix: /api
    resource: '@AppBundle/Resources/config/api-routing.yml'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"