# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        #@todo use bcrypt (need php 5.5)
        FOS\UserBundle\Model\UserInterface: sha512
            #iterations: 10

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        main:
            pattern: ^/
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check

            logout: true
            anonymous: true

        #api:
        #    pattern: ^/api
        #    context: api
        #    form_login:
        #       provider: fos_userbundle
        #        login_path: fos_user_security_login
        #        check_path: api_login_check
        #    logout: true
        #    anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }